//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockroomBinar.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliveries
    {
        public int ID { get; set; }
        public string СustomerТame { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> IDInside { get; set; }

        public string ReadyColor
        {
            get
            {
                if (Status == 100) return "Green";
                return "White";
            }
        }
        public string DateEdit
        {
            get
            {
                if (СustomerТame != null)
                {
                    return (Date.Value.Date.ToShortDateString()).ToString();
                }
                return Date.ToString();

            }
        }
    }
}
