//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockroomBinar.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveriesProducts
    {
        public int ID { get; set; }
        public Nullable<int> IDInside { get; set; }
        public string CodeDitals { get; set; }
        public Nullable<int> ReadyDitals { get; set; }
        public Nullable<int> NecessaryCountDitals { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> NumberPosition { get; set; }
        public string DescriptionOnStok { get; set; }
    }
}
