//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockroomBinar.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DitalesProduction
    {
        public int ID { get; set; }
        public string CodeDitales { get; set; }
        public Nullable<int> EngravingStatus { get; set; }
        public Nullable<int> CountOnStoock { get; set; }
        public Nullable<int> IDInside { get; set; }
    }
}
