//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockroomBinar.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDManufacturer
    {
        public int ID { get; set; }
        public string NameManufacturer { get; set; }
        public Nullable<int> IDInside { get; set; }
        public string NDS { get; set; }
        public string Country { get; set; }
        public string Quality { get; set; }
        public string SpeedDeliver { get; set; }
        public string Notes { get; set; }
        public string Site { get; set; }

        public string SiteVisibleButton
        {
            get
            {
                if (Site != null) return "Visible";
                return "Hidden";
            }
        }

        //public string SpeedColor
        //{
        //    get
        //    {
        //        if (SpeedDeliver == "Быстро") return "Green";
        //        if (SpeedDeliver == "Нормально") return "Yellow";
        //        if (SpeedDeliver == "Долго") return "Red";
        //        return "White";
        //    }
        //}

        public string ViewColor
        {
            get
            {
                if (IDInside % 2 == 0) return "#464451";
                return "Grey";
            }
        }
    }
}
