//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockroomBinar.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockroomBinarEntities : DbContext
    {
        public StockroomBinarEntities()
            : base("name=StockroomBinarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blueprints> Blueprints { get; set; }
        public virtual DbSet<ColorPlastic> ColorPlastic { get; set; }
        public virtual DbSet<DefectivePlastic> DefectivePlastic { get; set; }
        public virtual DbSet<Deliveries> Deliveries { get; set; }
        public virtual DbSet<DeliveriesProducts> DeliveriesProducts { get; set; }
        public virtual DbSet<DitalesProduction> DitalesProduction { get; set; }
        public virtual DbSet<ForPrinters> ForPrinters { get; set; }
        public virtual DbSet<IDManufacturer> IDManufacturer { get; set; }
        public virtual DbSet<IDPlasticProducts> IDPlasticProducts { get; set; }
        public virtual DbSet<IDProductsProduction> IDProductsProduction { get; set; }
        public virtual DbSet<NotesUser> NotesUser { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<PlasticProducts> PlasticProducts { get; set; }
        public virtual DbSet<PlasticStor> PlasticStor { get; set; }
        public virtual DbSet<PlasticType> PlasticType { get; set; }
        public virtual DbSet<ProductsForEngraving> ProductsForEngraving { get; set; }
        public virtual DbSet<Profiles> Profiles { get; set; }
        public virtual DbSet<RecyclingPlastic> RecyclingPlastic { get; set; }
        public virtual DbSet<StatisticOrders> StatisticOrders { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
