//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockroomBinar.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotesUser
    {
        public int ID { get; set; }
        public string Descriptions { get; set; }
        public Nullable<bool> Status { get; set; }

        public string DecorateNotes
        {
            get
            {
                if (Status == false) return "none";
                return "Strikethrough";
            }
        }
    }
}
