//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockroomBinar.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlasticProducts
    {
        public int ID { get; set; }
        public Nullable<decimal> ProductWeight { get; set; }
        public Nullable<decimal> SupportsWeight { get; set; }
        public Nullable<int> EngravingStatus { get; set; }
        public string TimePrint { get; set; }
        public string ProductTypeID { get; set; }
        public string ColorName { get; set; }
        public string TypePlasticPrint { get; set; }
        public string ManufacturerPlasticPrint { get; set; }
        public Nullable<int> CountOnStoock { get; set; }
        public Nullable<int> IDInside { get; set; }

        public string SumWeight
        {
            get
            {
                if (SupportsWeight != null) return (SupportsWeight + ProductWeight).ToString();
                return ProductWeight.ToString();
            }
        }
    }
}
