//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockroomBinar.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profiles
    {
        public int ID { get; set; }
        public string NameProfile { get; set; }
        public Nullable<int> Type { get; set; }
        public string Folder { get; set; }
        public string Materials { get; set; }
    }
}
