//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockroomBinar.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecyclingPlastic
    {
        public int ID { get; set; }
        public string ColorNameRecucling { get; set; }
        public string PlasticTypeRecucling { get; set; }
        public string ManufacturerRecucling { get; set; }
        public Nullable<decimal> WeightRecucling { get; set; }
        public Nullable<int> PlasticStatus { get; set; }
        public Nullable<bool> StatusRecucling { get; set; }
        public Nullable<int> IDInside { get; set; }
    }
}
