//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockroomBinar.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticOrders
    {
        public int ID { get; set; }
        public string NameDitales { get; set; }
        public Nullable<int> ReadyCount { get; set; }
        public Nullable<int> NeseseryCount { get; set; }
    }
}
